version: '2'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - DEST_PROJECT_URL
      - DEST_STORAGE_API_TOKEN
      - DEST_STORAGE_API_TOKEN_NOT_MASTER
      - SOURCE_PROJECT_URL
      - SOURCE_STORAGE_API_ADMIN_TOKEN
