services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_URL
      - KBC_TOKEN
      - KBC_TOKEN_NOT_MASTER
      - SOURCE_PROJECT_URL
      - SOURCE_STORAGE_API_ADMIN_TOKEN
